# Generated by Django 4.0.6 on 2022-07-13 21:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150, verbose_name='User')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('description', models.CharField(max_length=750, verbose_name='description')),
                ('image', models.CharField(default='banner.jpg', max_length=256)),
                ('price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='price')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('state', models.CharField(max_length=100, verbose_name='state')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('street', models.CharField(max_length=100, verbose_name='street')),
                ('postal', models.CharField(max_length=5, verbose_name='postal')),
                ('slug', models.SlugField(max_length=150, verbose_name='slug')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
