# Generated by Django 4.0.6 on 2022-07-20 19:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('description', models.CharField(max_length=750, verbose_name='description')),
                ('organizer', models.CharField(max_length=32, verbose_name='organizer')),
                ('type', models.CharField(choices=[('CON', 'Academic'), ('FAI', 'Fair'), ('FES', 'Festival'), ('PAR', 'Party'), ('SEM', 'Seminar'), ('COM', 'Competition'), ('OTH', 'Other')], default='OTH', max_length=3, verbose_name='type')),
                ('category', models.CharField(choices=[('CAR', 'Career'), ('CMM', 'Community'), ('CUL', 'Culture'), ('EDU', 'Educational'), ('WOR', 'Workshop'), ('SPE', 'Special Interest'), ('OTH', 'Other')], default='OTH', max_length=3, verbose_name='category')),
                ('image', models.CharField(default='banner.jpg', max_length=256)),
                ('price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='price')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('state', models.CharField(max_length=100, verbose_name='state')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('street', models.CharField(max_length=100, verbose_name='street')),
                ('postal', models.CharField(max_length=5, verbose_name='postal')),
                ('slug', models.SlugField(max_length=150, verbose_name='slug')),
                ('qr', models.CharField(blank=True, max_length=256, null=True, verbose_name='qr code')),
                ('following', models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='participants', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
