# Generated by Django 4.0.6 on 2022-07-12 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='cordinator',
            new_name='coordinator',
        ),
    ]
